name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: |
          git config user.name savosya
          git config user.email savosapple@mail.ru
          npm version ${{ github.event.inputs.version }}
          git push origin main
          git push origin v${{ github.event.inputs.version }}
      - run: yarn build
      - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}